spring.application.name=Trading_Bot
#server.port=8080
server.port=${SERVER_PORT:8082}
#Log4jPath = C:\Users\HaiderAliKhan\Downloads\TradingBotV4_Logs
Log4jPath = ${LOG_PATH:NoValueFound}
delta.base.url=https://api.india.delta.exchange
delta.symbol=BTCUSD
delta.loop.interval=5
delta.order.size=0.001

#MAIN ACCOUNT DETAILS
#delta.api.key=QkcozvN7XM6uzcRC5lREH6rdDXQI4i
#delta.api.secret=IeWvF36I8wABBseGQwKZ9OoR3THYbDt78jfeCU8aj78iuXSCBbeOYHGtDaC5

#SHORT ACCOUNT DETAILS
#delta.api.key=GIW1raNFd4iY9CDWemOt2HdZFIAuNj
#delta.api.secret=07PkTvdkUC4EuMrLAwn4qib77XlReOoUmj879tmKO2ar0BMNzv6qdtZOM4mp
delta.api.key=${DELTA_API_KEY:NoValueFound}
delta.api.secret=${DELTA_API_SECRET:NoValueFound}

delta.api.productid=27
delta.api.getorderlimit=20